// Interface to represent our Quote Object
export type QuoteHeader = {
  QuoteID: number;
  QuoteNumber: string;
  CustID: string;
  QuoteCSR?: string;
  SalesRep?: string;
  QuoteUser: string;
  QuoteDate: string;
  AutoLength: boolean;
  ValidLength: number;
  DefaultPricing?: number;
  MultipliersID: number;
  PublicBid: boolean;
  QuoteMultiplier: number;
  PublicMultiplier: number;
  MultipliersDate: string;
  SpecialPricingEnabled: boolean;
  BidCatalogPrice: boolean;
  BidPriceMultiplier: number;
  BidHeader: any;
  BillInfo?: string;
  Comments: string;
  PrivateComments: string;
  ShipDate?: string;
  ShipName?: string;
  ShipAddr1?: string;
  ShipAddr2?: string;
  ShipCity?: string;
  ShipState?: string;
  ShipZIP?: string;
  ShipCountry?: string;
  ShipPhone?: string;
  ShipEmail?: string;
  ShipVia?: string;
  ShipMethod?: string;
  FreightAmount?: number;
  Gyms: number;
  OldGyms: number;
  Private: boolean;
  Deleted: boolean;
  DeleteDate?: string;
  ConvertRequest: boolean;
  PONumber?: string;
  Converted: boolean;
  ConvertDate?: string;
  ConvertEscalationPercent?: number;
  Lost: boolean;
  Status?: string;
  Lock: boolean;
  LockAmount?: number;
  BidDate?: string;
  BidTypeOld: any;
  QuotedOld: any;
  BidStatus?: string;
  LeadType?: string;
  BidType?: string;
  Quoted?: string;
  Market?: string;
  Migrated: boolean;
};

export type LineComponent = {
  LineConfigID: number;
  QuoteID: number;
  GymNumber: number;
  LineID: number;
  LineConfigNum: number;
  PartNumber: string;
  PartDescription: string;
  Quantity: number;
  Cost: number;
  Weight: number;
};

// The state of our Quote Header data
export type QuoteHeaderState = {
  loading: boolean;
  ageSelection: number;
  currentQuote: QuoteHeader | {};
};
export type QuoteLine = {
  LineID: number;
  QuoteID: number;
  LineNumber: number;
  PartNum: string;
  Enabled: boolean;
  LineTypeID: number;
  Quantity: number;
  Weight: number;
  ItemCost: number;
  OrderCost?: number;
  ManualPrice?: number;
  SchoolPrice?: any;
  DefaultPrice?: any;
  UnitPrice?: number;
  ITPBExempt: boolean;
  PricingMode?: any;
  MultipliersID: number;
  Bid1?: any;
  Bid2?: any;
  Bid3?: any;
  CostPlusMultiplier: number;
  LineMultiplier: number;
  Configured: boolean;
  ConfigText?: string;
  CSIText?: any;
  ManualConfigured: boolean;
  ManualText?: any;
  ManualUser?: any;
  ManualDate?: any;
  SaveData?: any;
  ACGymID?: number;
  ACItemID?: string;
  ConvertPrice?: any;
  ExtendedText?: any;
  GymLock: boolean;
  TrueCost?: any;
  PriceBookPrice?: any;
  PartDescription?: string;
  IUM?: string;
  TotalRolledCost?: number;
  PartMasterPrice?: number;
  LineTotal?: number;
};
// The state of our Quoter
export type QuoteLineState = {
  loading: boolean;
  totalPrice: number;
  compList: Array<LineComponent>;
};
