// // Interface to represent our Quote Object
// export type QuoteHeader = {
//   QuoteID: number;
//   QuoteNumber: string;
//   CustID: string;
//   QuoteCSR?: string;
//   SalesRep?: string;
//   QuoteUser: string;
//   QuoteDate: Date;
//   AutoLength: boolean;
//   ValidLength: number;
//   DefaultPricing?: number;
//   MultipliersID: number;
//   PublicBid: boolean;
//   QuoteMultiplier: number;
//   PublicMultiplier: number;
//   MultipliersDate: string;
//   SpecialPricingEnabled: boolean;
//   BidCatalogPrice: boolean;
//   BidPriceMultiplier: number;
//   BidHeader: any;
//   BillInfo?: string;
//   Comments: string;
//   PrivateComments: string;
//   ShipDate?: Date;
//   ShipName?: string;
//   ShipAddr1?: string;
//   ShipAddr2?: string;
//   ShipCity?: string;
//   ShipState?: string;
//   ShipZIP?: string;
//   ShipCountry?: string;
//   ShipPhone?: string;
//   ShipEmail?: string;
//   ShipVia?: string;
//   ShipMethod?: string;
//   FreightAmount?: number;
//   Gyms: number;
//   OldGyms: number;
//   Private: boolean;
//   Deleted: boolean;
//   DeleteDate?: string;
//   ConvertRequest: boolean;
//   PONumber?: string;
//   Converted: boolean;
//   ConvertDate?: string;
//   ConvertEscalationPercent?: number;
//   Lost: boolean;
//   Status?: string;
//   Lock: boolean;
//   LockAmount?: number;
//   BidDate?: Date;
//   BidTypeOld: any;
//   QuotedOld: any;
//   BidStatus?: string;
//   LeadType?: string;
//   BidType?: string;
//   Quoted?: string;
//   Market?: string;
//   Migrated: boolean;
// };
// Interface to represent our Quote Object
export type QuoteHeader = {
  quote_id: number;
  quote_number: string;
  cust_id: string;
  quote_csr?: string;
  sales_rep?: string;
  quote_user: string;
  quote_date: Date;
  auto_length: boolean;
  valid_length: number;
  default_pricing?: number;
  multipliers_id: number;
  public_bid: boolean;
  quote_multiplier: number;
  public_multiplier: number;
  multipliers_date: string;
  special_pricing_enabled: boolean;
  bid_catalog_price: boolean;
  bid_price_multiplier: number;
  bid_header: any;
  bill_info?: string;
  comments: string;
  private_comments: string;
  ship_date?: Date;
  ship_name?: string;
  ship_addr1?: string;
  ship_addr2?: string;
  ship_city?: string;
  ship_state?: string;
  ship_zip?: string;
  ship_country?: string;
  ship_phone?: string;
  ship_email?: string;
  ship_via?: string;
  ship_method?: string;
  freight_amount?: number;
  gyms: number;
  old_gyms: number;
  private: boolean;
  deleted: boolean;
  delete_date?: string;
  convert_request: boolean;
  po_number?: string;
  converted: boolean;
  convert_date?: string;
  convert_escalation_percent?: number;
  lost: boolean;
  status?: string;
  lock: boolean;
  lock_amount?: number;
  bid_date?: Date;
  bid_type_old: any;
  quoted_old: any;
  bid_status?: string;
  lead_type?: string;
  bid_type?: string;
  quoted?: string;
  market?: string;
  migrated: boolean;
  quote_total_val?: number;
};

export type LineComponent = {
  LineConfigID: number;
  QuoteID: number;
  GymNumber: number;
  LineID: number;
  LineConfigNum: number;
  PartNumber: string;
  PartDescription: string;
  Quantity: number;
  Cost: number;
  Weight: number;
};

// The state of our Quote Header data
export type QuoteHeaderState = {
  loading: boolean;
  ageSelection: number;
  adminEnabled: boolean;
  currentQuote: QuoteHeader | Partial<QuoteHeader>;
};
export type QuoteLine = {
  line_id: number;
  quote_id: number;
  line_number: number;
  part_num: string;
  enabled: boolean;
  line_type_id: number;
  quantity: number;
  weight: number;
  item_cost: number;
  order_cost?: number;
  manual_price?: number;
  school_price?: any;
  default_price?: any;
  unit_price?: number;
  itpb_exempt: boolean;
  pricing_mode?: any;
  multipliers_id: number;
  bid1?: any;
  bid2?: any;
  bid3?: any;
  cost_plus_multiplier: number;
  line_multiplier: number;
  configured: boolean;
  config_text?: string;
  csi_text?: any;
  manual_configured: boolean;
  manual_text?: any;
  manual_user?: any;
  manual_date?: any;
  save_data?: any;
  ac_gym_id?: number;
  ac_item_id?: string;
  converted_price?: any;
  extended_text?: any;
  gym_lock: boolean;
  true_cost?: any;
  pricebook_price?: any;
  part_description?: string;
  ium?: string;
  total_rolled_cost?: number;
  part_master_price?: number;
  line_total?: number;
};
// The state of our Quoter
export type QuoteLineState = {
  loading: boolean;
  totalPrice: number;
  compList: Array<LineComponent>;
};
